I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 281, in script
    lisa {i} "Делает затяжку и протягивает вам чуйку.{/i}"
Exception: Sayer 'lisa {i}' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 281, in script
    lisa {i} "Делает затяжку и протягивает вам чуйку.{/i}"
  File "/home/miksolo/renpy/engine/renpy-8.0.3-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/miksolo/renpy/engine/renpy-8.0.3-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'lisa {i}' is not defined.

Linux-5.15.0-60-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.0.3.22090809
Что то на русском 1.0
Sun Feb 12 14:25:05 2023
